language: go

sudo: required

services:
  - docker

go:
  - "1.10"

install:
  - go get -u golang.org/x/lint/golint
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

script:
  - golint -set_exit_status ./cmd/... ./internal/...
  - go test -v ./...
  - docker build -t cpudp -f build/Dockerfile.cpudp .
  - docker build -t cpu-device-webhook -f build/Dockerfile.webhook .
  - CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static"' github.com/nokia/CPU-Pooler/cmd/process-starter
